/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcolegio.Forms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jcolegio.Conexion;


/**
 *
 * @author osaomi
 */
public class cicloEscolar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CicloEscolar
     */
    public cicloEscolar() {
        initComponents();
        
      
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFecha = new javax.swing.JLabel();
        TextAño = new javax.swing.JTextField();
        buttonCicloE = new javax.swing.JButton();
        cerrarInscripcion = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setTitle("Ciclo Escolar");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/calendar_32.png"))); // NOI18N

        LabelFecha.setText("Ciclo Escolar:");

        buttonCicloE.setText("Guardar");
        buttonCicloE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCicloEActionPerformed(evt);
            }
        });

        cerrarInscripcion.setText("Cerrar");
        cerrarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarInscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextAño))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(buttonCicloE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarInscripcion)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCicloE)
                    .addComponent(cerrarInscripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCicloEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCicloEActionPerformed
        // TODO add your handling code here:
         if(this.TextAño.getText().isEmpty() == false ){ //agregar && this.jTextField3.getText().isEmpty()==false
            try {
                Conexion conec2 = new Conexion();
                conec2.ingresar ("INSERT INTO cicloescolar (`año`) " + " VALUES  ('"+this.TextAño.getText()+"')");
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Datos guardados correctamente", "Guardando", 1);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(alumnoInscripcion.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else{
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Error Debe llenar ingresar el ciclo escolar", "Error", 0);
        }
    }//GEN-LAST:event_buttonCicloEActionPerformed

    private void cerrarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarInscripcionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cerrarInscripcionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JTextField TextAño;
    private javax.swing.JButton buttonCicloE;
    private javax.swing.JButton cerrarInscripcion;
    // End of variables declaration//GEN-END:variables
Conexion conec = new Conexion();

}
