/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcolegio.Forms;

/**
 *
 * @author unno
 */
public class exploradorAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form exploradorAlumnos
     */
    public exploradorAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbgrad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcbsec = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jcbcicl = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clase"));

        jLabel1.setText("Grado:");

        jcbgrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbgradActionPerformed(evt);
            }
        });

        jLabel3.setText("Sección:");

        jcbsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsecActionPerformed(evt);
            }
        });

        jLabel5.setText("Ciclo Escolar");

        jcbcicl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbciclActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Cargar datos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jcbgrad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbcicl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbsec, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbgrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcbsec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbcicl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jButton2.setText("Ingresar Notas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Imprimir todos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbgradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbgradActionPerformed
        if(this.jcbgrad.getItemCount()>0){
            try {
                Conexion conect3 = new Conexion();
                ResultSet rs3;
                rs3 = conect3.consul("select Id from grado_carrera where Grado_idGrado ="+this.djcgrad.getElementAt(this.jcbgrad.getSelectedIndex())+" and Carrera_idCarrera ="+this.djccarr.getElementAt(this.jcbCarr.getSelectedIndex())+";" );
                djcsec.removeAllElements();
                this.jcbsec.removeAllItems();
                if(rs3.next()){
                    int temp2 =rs3.getInt(1);
                    rs3 = conect3.consul("select Letra, seccion_g_c.idSeccion_G_C from seccion inner join seccion_g_c on seccion_g_c.Seccion_idSeccion = seccion.idSeccion and seccion_g_c.Grado_Carrera_Id = "+temp2+" order by Seccion_idSeccion asc;");
                    while(rs3.next()){
                        this.jcbsec.addItem(rs3.getString(1));
                        djcsec.addElement(rs3.getInt(2));
                    }
                }
                if(this.jcbsec.getItemCount()>0){
                    this.jcbsec.setSelectedIndex(0);
                }
                this.jButton4ActionPerformed(evt);
            } catch (SQLException ex) {
                Logger.getLogger(Frmiexplorer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jcbgradActionPerformed

    private void jcbsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsecActionPerformed
        // TODO add your handling code here:
        if(this.jcbsec.getSelectedIndex()!=-1){
            this.jButton4ActionPerformed(evt);
        }
    }//GEN-LAST:event_jcbsecActionPerformed

    private void jcbciclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbciclActionPerformed
        // TODO add your handling code here:
        if(this.jcbcicl.getSelectedIndex()!=-1){

            this.jButton4ActionPerformed(evt);
        }
    }//GEN-LAST:event_jcbciclActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if(this.jcbCarr.getSelectedIndex() != -1 && this.jcbgrad.getSelectedIndex() != -1 && this.jcbsec.getSelectedIndex() != -1 && this.jcbcicl.getSelectedIndex() != -1 ){
                Conexion conect4 = new Conexion();
                ResultSet rs4; //)
            rs4 = conect4.consul("select count(asignacion.idAsignacion) from alumno inner join asignacion on Seccion_G_C_idSeccion_G_C = "+djcsec.getElementAt(this.jcbsec.getSelectedIndex())+" and Cicloesc_idCicloesc = "+this.djccicl.getElementAt(this.jcbcicl.getSelectedIndex()) +" where idAlumno = Alumno_idAlumno order by alumno.Apellido , alumno.Nombre  ;");
            rs4.next();
            int temp = rs4.getInt(1), inc=0;
            rs4 = conect4.consul("select asignacion.Clave, alumno.Apellido, alumno.Nombre, asignacion.idAsignacion, alumno.idAlumno from alumno inner join asignacion on Seccion_G_C_idSeccion_G_C = "+djcsec.getElementAt(this.jcbsec.getSelectedIndex())+" and Cicloesc_idCicloesc = "+this.djccicl.getElementAt(this.jcbcicl.getSelectedIndex()) +" where idAlumno = Alumno_idAlumno order by alumno.Apellido , alumno.Nombre  ;");
            Vector = new String[temp][3];
            asig.removeAllElements();
            idalum.removeAllElements();
            while (rs4.next()){
                idalum.addElement(rs4.getInt(5));
                Vector[inc][0]= String.valueOf(rs4.getInt(1));
                Vector[inc][1]= rs4.getString(2);
                Vector[inc][2]= rs4.getString(3);
                asig.addElement(rs4.getInt(4));
                inc++;
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                Vector,
                new String [] {
                    "Clave", "Apellidos", "Nombres"
                }
            )
            {
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });

        }

        } catch (SQLException ex) {
            Logger.getLogger(Frmiexplorer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jTable1.getSelectedRow()!=-1){
            if(frmmain.jDesktopPane1.getIndexOf(v9)== -1 ){
                v9 = new jalumnos.frmAplicacion.frmnotas(Integer.valueOf(String.valueOf(asig.getElementAt(this.jTable1.getSelectedRow()))),this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 1)+", "+this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 2),this.jcbCarr.getSelectedItem().toString(), this.jcbgrad.getSelectedItem().toString(),this.jcbsec.getSelectedItem().toString(), this.jcbcicl.getSelectedItem().toString(),this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 0).toString(),asig.getElementAt(this.jTable1.getSelectedRow()).toString());
                frmmain.jDesktopPane1.add(v9);
                v9.show();
            }else{
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Error ya existe una ventana abierta", "Error", 1);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Conexion connect = new Conexion();
        Conexion connect2 = new Conexion();
        ResultSet rs;
        ResultSet rs2;
        int nota1,nota2,nota3,nota4,prom;
        try {
            connect.ingresar("TRUNCATE printnota");
            connect.ingresar("TRUNCATE printnotaalumno");
            for(int i =0; i<this.asig.getSize();i++){
                connect.ingresar("INSERT INTO `printnotaalumno` (`IdAlumno`, `Nombres`, `Carrera`, `Grado`, `Seccion`, `Ciclo`, `Clave`) VALUES ("+asig.getElementAt(i) +", '"+this.jTable1.getValueAt(i, 1) + " " + this.jTable1.getValueAt(i, 2) +"', '"+this.jcbCarr.getSelectedItem()+"', '"+this.jcbgrad.getSelectedItem()+"', '"+this.jcbsec.getSelectedItem()+"', '"+this.jcbcicl.getSelectedItem()+"', '"+this.jTable1.getValueAt(i, 0) +"');");
                rs=connect.consul("select nota,Divicion_id,Cursos_idCursos from basejalumnos.notas where Asignacion_idAsignacion ="+asig.getElementAt(i) +" order by Cursos_idCursos, Divicion_id");
                while(rs.next()){
                    prom=0;
                    nota1=rs.getInt(1);
                    rs.next();
                    nota2=rs.getInt(1);
                    rs.next();
                    nota3=rs.getInt(1);
                    rs.next();
                    nota4=rs.getInt(1);
                    rs2 = connect2.consul("select Nombre from basejalumnos.cursos where idCursos ="+rs.getInt(3));
                    rs2.next();
                    prom = nota1+nota2+nota3+nota4;
                    prom = prom/4;
                    connect2.ingresar("INSERT INTO `basejalumnos`.`printnota` (`PrintNotaalumno_IdAlumno`, `Curso`, `nota1`, `nota2`, `nota3`, `nota4`, `promedio`) VALUES ("+asig.getElementAt(i) +", '"+rs2.getString(1) +"', "+nota1 +", "+nota2 +", "+nota3 +", "+nota4 +", "+prom+");");

                }
            }

            reporte.startReport();
        } catch (SQLException ex) {
            Logger.getLogger(frmnotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.jTable1.getRowCount()>0){
            Conexion conect6 = new Conexion();
            for(int a =0; a< this.jTable1.getRowCount();a++){
                try {
                    conect6.ingresar("UPDATE `basejalumnos`.`asignacion` SET `Clave`="+this.jTable1.getValueAt(a, 0) +" WHERE `idAsignacion`="+asig.getElementAt(a)+";");
                } catch (SQLException ex) {
                    Logger.getLogger(Frmiexplorer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Claves Guardadas", "Estado del Proceso", 1);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcbcicl;
    private javax.swing.JComboBox jcbgrad;
    private javax.swing.JComboBox jcbsec;
    // End of variables declaration//GEN-END:variables
}
