/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcolegio.Forms;

import java.sql.ResultSet;
import java.util.Vector;
import jcolegio.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author osaomi
 */
public final class grado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Grado
     */
    public void Actualizar(){
        
        try {
            jcId.removeAllElements();
            jcDesc.removeAllElements();
            ResultSet rs1;
            rs1 = conect.consul("SELECT id, descripcion FROM canem.grado;");
            while(rs1.next()){
                jcId.addElement(rs1.getObject(1));
                jcDesc.addElement(rs1.getObject(2));
            }
           jcmbGrado.setModel(jcDesc);
        } catch (SQLException ex) {
            Logger.getLogger(grado.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcmbGradoActionPerformed(null);
    }
    public grado() {
        initComponents();
        jlsAsig.setModel(jlAsigDesc);
        jlsDisp.setModel(jlDispDesc);
        Actualizar();
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelGradoN = new javax.swing.JLabel();
        TextGradoN = new javax.swing.JTextField();
        buttonEnviarG = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmbGrado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlsAsig = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlsDisp = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setClosable(true);
        setTitle("Grados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/whiteboard_32.png"))); // NOI18N

        LabelGradoN.setText("Grado:");

        TextGradoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextGradoNActionPerformed(evt);
            }
        });

        buttonEnviarG.setText("Guardar");
        buttonEnviarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnviarGActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar secciones"));

        jLabel2.setText("Grado:");

        jcmbGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbGradoActionPerformed(evt);
            }
        });

        jLabel3.setText("Disponibles");

        jScrollPane1.setViewportView(jlsAsig);

        jButton2.setText("Agregar >>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<< Quitar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jlsDisp);

        jLabel4.setText("Asignados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEnviarG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LabelGradoN)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TextGradoN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGradoN)
                    .addComponent(TextGradoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonEnviarG))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextGradoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextGradoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextGradoNActionPerformed

    private void buttonEnviarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnviarGActionPerformed
        // TODO add your handling code here:
        try {
            if(deleteItem){
                ResultSet rs1 = conect.consul("select sg.id, s.id from seccion as s inner join secciongrado as sg on sg.seccion_id = s.id where sg.grado_id = " + jcId.getElementAt(jcmbGrado.getSelectedIndex()));
                while(rs1.next()){
                    if(jlAsigId.contains(rs1.getObject(2))==false){
                        conect.ingresar("DELETE FROM `secciongrado` WHERE `id`=" +rs1.getObject(1) );
                        rs1 = conect.consul("select sg.id, s.id from seccion as s inner join secciongrado as sg on sg.seccion_id = s.id where sg.grado_id = " + jcId.getElementAt(jcmbGrado.getSelectedIndex()));
                    }
                }
            }
            for(int i=0; i<jlAsigId.getSize();i++){
                ResultSet rs1 = conect.consul("select sg.id from secciongrado as sg  where sg.grado_id = " 
                        + jcId.getElementAt(jcmbGrado.getSelectedIndex()) + " and sg.seccion_id = "+jlAsigId.getElementAt(i));
                if(!(rs1.next())){
                    conect.ingresar("INSERT INTO `canem`.`secciongrado` (`seccion_id`, `grado_id`) VALUES ("+jlAsigId.getElementAt(i)+", " 
                        + jcId.getElementAt(jcmbGrado.getSelectedIndex()) + " );");
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Datos Ingresados", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(grado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonEnviarGActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        if(this.TextGradoN.getText().isEmpty() == false && jcDesc.getIndexOf(TextGradoN.getText())==-1 ){ //agregar && this.jTextField3.getText().isEmpty()==false
            try {
                Conexion conec2 = new Conexion();
                conec2.ingresar ("INSERT INTO grado (`descripcion`) " + " VALUES  ('"+this.TextGradoN.getText()+"')");
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Datos guardados correctamente", "Guardando", 1);
                Actualizar();
                TextGradoN.setText("");
                
            } catch (SQLException ex) {
                Logger.getLogger(grado.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }else{
            TextGradoN.setText("");
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Error Debe llenar el nombre del grado", "Error", 0);
        }    

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcmbGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbGradoActionPerformed
        if(jcmbGrado.getSelectedIndex()>-1){
            try {
                ResultSet rs1 = conect.consul("select s.id, s.descripcion from seccion as s where not exists (select * from secciongrado as sg where sg.grado_id = "
                        +jcId.getElementAt(jcmbGrado.getSelectedIndex()).toString() + " and sg.seccion_id = s.id) order by  s.descripcion asc ");
                jlDispId.removeAllElements();
                jlDispDesc.removeAllElements();
                while (rs1.next()){
                    jlDispId.addElement(rs1.getObject(1));
                    jlDispDesc.addElement(rs1.getObject(2));
                }
                rs1 = conect.consul("select s.id, s.descripcion from seccion as s inner join secciongrado as sg on sg.seccion_id = s.id where sg.grado_id = "+jcId.getElementAt(jcmbGrado.getSelectedIndex()).toString() );
                jlAsigId.removeAllElements();
                jlAsigDesc.removeAllElements();
                while (rs1.next()){
                    jlAsigId.addElement(rs1.getObject(1));
                    jlAsigDesc.addElement(rs1.getObject(2));
                }
                deleteItem = false;
            } catch (SQLException ex) {
                Logger.getLogger(grado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jcmbGradoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          //agregando a la lista
        if(this.jlsDisp.getSelectedIndex() > -1){
           jlAsigId.addElement(jlDispId.getElementAt(jlsDisp.getSelectedIndex()));
           jlAsigDesc.addElement(jlDispDesc.getElementAt(jlsDisp.getSelectedIndex()));
           jlDispId.removeElementAt(jlsDisp.getSelectedIndex());
           jlDispDesc.removeElementAt(jlsDisp.getSelectedIndex());
           
        }else{
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Debe seleccionar alómenos un elemento", "Error", 1);
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(this.jlsAsig.getSelectedIndex() > -1){
           jlDispId.addElement(jlAsigId.getElementAt(jlsAsig.getSelectedIndex()));
           jlDispDesc.addElement(jlAsigDesc.getElementAt(jlsAsig.getSelectedIndex()));
           jlAsigId.removeElementAt(jlsAsig.getSelectedIndex());
           jlAsigDesc.removeElementAt(jlsAsig.getSelectedIndex());
           deleteItem = true;
        }else{
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Debe seleccionar alómenos un elemento", "Error", 1);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelGradoN;
    private javax.swing.JTextField TextGradoN;
    private javax.swing.JButton buttonEnviarG;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcmbGrado;
    private javax.swing.JList jlsAsig;
    private javax.swing.JList jlsDisp;
    // End of variables declaration//GEN-END:variables
    Conexion conect = new Conexion();
    javax.swing.DefaultComboBoxModel jcId = new javax.swing.DefaultComboBoxModel<>();
    javax.swing.DefaultComboBoxModel jcDesc = new javax.swing.DefaultComboBoxModel<>();
    Vector v1 = new Vector();
    Vector v2 = new Vector();
    javax.swing.DefaultComboBoxModel jl2 = new javax.swing.DefaultComboBoxModel<>();
    javax.swing.DefaultComboBoxModel jl1 = new javax.swing.DefaultComboBoxModel<>();
    //Asignacion de secciones
    javax.swing.DefaultListModel jlDispId = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultListModel jlDispDesc = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultListModel jlAsigId = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultListModel jlAsigDesc = new javax.swing.DefaultListModel<>();
    Boolean deleteItem = false;
}
